# Workflow setup for building Native Android project
workflows:
  android-app: # workflow ID
    name: Android app # workflow name
    max_build_duration: 120
    instance_type: mac_mini_m2
    scripts:
      - ./gradlew assembleDebug
    artifacts:
      - build/outputs/**/**/*.apk